about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

posts/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('404/', views.page_not_found, name='handler404'),
    path('500/', views.server_error, name='handler500'),
    path('follow/', views.follow_index, name='follow_index'),
    path('<str:username>/follow/', views.profile_follow,
         name='profile_follow'),
    path('<str:username>/unfollow/', views.profile_unfollow,
         name='profile_unfollow'),
    path('group/<slug:slug>/', views.group_posts, name='group'),
    path('new/', views.new_post, name='new_post'),
    path('<str:username>/', views.profile, name='profile'),
    path('<str:username>/<int:post_id>/', views.post_view, name='post'),
    path(
        '<str:username>/<int:post_id>/edit/',
        views.post_edit,
        name='post_edit'
    ),
    path(
        '<username>/<int:post_id>/comment',
        views.add_comment,
        name='add_comment'
    ),

]

yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500

handler404 = "posts.views.page_not_found"
handler500 = "posts.views.server_error"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        "Название группы",
        max_length=200,
        help_text='Дайте короткое название группе'
    )
    slug = models.SlugField(
        "Уникальное имя",
        unique=True,
        help_text='Укажите адрес для страницы задачи.'
    )
    description = models.TextField(
        "Описание",
        help_text='Дайте описание группе'
    )

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        "Текст",
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        "Дата публикации",
        auto_now_add=True,
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="posts",
        verbose_name="Пользователь"
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.CASCADE,
        related_name="posts",
        blank=True,
        null=True,
        verbose_name="Группа",
        help_text='Выберите группу'
    )
    image = models.ImageField(upload_to='posts/', blank=True, null=True)

    class Meta:
        ordering = ('-pub_date',)

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="comments",
        verbose_name="Пользователь"
    )
    text = models.TextField(
        "Текст",
        help_text='Введите текст комментария'
    )
    created = models.DateTimeField(
        "Дата публикации",
        auto_now_add=True,
    )


class Follow(models.Model):
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             blank=False,
                             null=False,
                             related_name='follower')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               blank=False,
                               null=False,
                               related_name='following')

posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    def clean_text(self):
        data = self.cleaned_data['text']
        if data == '':
            raise forms.ValidationError('Обязательно заполните поле')

        return data

    class Meta:
        model = Post
        fields = ['group', 'text', 'image']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        widget = {'text': forms.Textarea(attrs={'cols': 80, 'rows': 20})}

posts/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import PostForm, CommentForm

from .models import Group, Post, Comment, Follow


def index(request):
    latest = Post.objects.all()
    paginator = Paginator(latest, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(
        request,
        'index.html',
        {'page': page}
    )


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)

    return render(request, 'group.html',
                  {'page': page, 'group': group, 'posts': posts})


@login_required
def new_post(request):
    form = PostForm(request.POST or None,
                    files=request.FILES or None)
    if request.method == 'POST':
        form = PostForm(request.POST or None,
                        files=request.FILES or None)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('index')
    return render(request, 'new.html', {'form': form})


def profile(request, username):
    profile = get_object_or_404(User, username=username)
    post_list = profile.posts.all()
    counter_post = post_list.count()
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    following = (request.user.is_authenticated and
                 Follow.objects.filter(user=request.user,
                                       author=profile).exists())

    return render(request, 'profile.html',
                  {'profile': profile, 'counter_post': counter_post,
                   'page': page,
                   'following': following})


def post_view(request, username, post_id):
    profile = get_object_or_404(User, username=username)
    post = get_object_or_404(Post, id=post_id)
    comments = Comment.objects.filter(post=post)
    form = CommentForm()
    context = {
        'post': post,
        'profile': profile,
        'comments': comments,
        'form': form,
    }
    return render(request, 'post.html', context)


@login_required
def post_edit(request, username, post_id):
    post = get_object_or_404(Post, id=post_id, author=request.user)
    form = PostForm(request.POST or None,
                    files=request.FILES or None, instance=post)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
        return redirect('post', username=post.author.username, post_id=post.id)

    return render(request, 'new.html', {'form': form, 'post': post})


def page_not_found(request, exception):
    return render(
        request,
        'misc/404.html',
        {'path': request.path},
        status=404
    )


def server_error(request):
    return render(request, 'misc/500.html', status=500)


@login_required
def add_comment(request, username, post_id):
    form = CommentForm(request.POST or None)
    post = get_object_or_404(Post, id=post_id, author=request.user)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('post', username, post_id)


@login_required
def follow_index(request):
    """Страница постов подписанных авторов."""
    post_follower = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(post_follower, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, 'follow.html',
                  {'page': page, 'paginator': paginator})


@login_required
def profile_follow(request, username):
    """Подписка на автора."""
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.get_or_create(user_id=request.user.id,
                                     author_id=author.id)
    return redirect('profile', username=username)


@login_required
def profile_unfollow(request, username):
    """Отписка от автора."""
    author = get_object_or_404(User, username=username)
    follow = Follow.objects.filter(user_id=request.user.id,
                                   author_id=author.id)
    follow.delete()
    return redirect('profile', username=username)

templates/author_card.html
<main role="main" class="container">
    <div class="row">
            <div class="col-md-3 mb-3 mt-1">
                    <div class="card">
                            <div class="card-body">
                                    <div class="h2">
                                        <!-- Имя автора -->
                                            {{ profile.get_full_name }}

                                    </div>
                                    <div class="h3 text-muted">
                                         <!-- username автора -->
                                         @{{ profile.username }}
                                    </div>
                            </div>
                            <ul class="list-group list-group-flush">
                                    <li class="list-group-item">
                                            <div class="h6 text-muted">
                                            Подписчиков: {{profile.following.count}} <br />
                                            Подписан: {{profile.follower.count}}
                                            </div>
                                    </li>
                                    <li class="list-group-item">
                                            <div class="h6 text-muted">
                                                <!-- Количество записей -->
                                                Записей: {{ profile.posts.count }}
                                            </div>

                                    <li class="list-group-item">


    {% if following %}
    <a class="btn btn-lg btn-light"
            href="{% url 'profile_unfollow' profile.username %}" role="button">
            Отписаться
    </a>
                                {% else %}
    <a class="btn btn-lg btn-primary"
            href="{% url 'profile_follow' profile.username %}" role="button">
    Подписаться
    </a>
        {% endif %}
</li>

                    </div>
            </div>

templates/base.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}The Last Social Media You'll Ever Need{% endblock %} | Yatube</title>
        <!-- Загрузка статики -->
        {% load static %}
        <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
        <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
        <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
    </head>
    <body>
        {% include 'nav.html' %}

        <main>
            <div class="container">
                <h1>{% block header %}{% endblock %}</h1>
                {% block content %}

                {% endblock content %}
            </div>

        </main>
        {% include 'footer.html' %}
    </body>
</html>

templates/comments.html
{% extends "base.html" %}
{% block content %}
{% load user_filters %}
<!-- Форма добавления комментария -->

{% if user.is_authenticated %}
<div class="card my-4">
    <form method="post">
        {% csrf_token %}
        <h5 class="card-header">Добавить комментарий:</h5>
        <div class="card-body">
            <div class="form-group">
                {{ form.text|addclass:"form-control" }}
            </div>
            <button type="submit" class="btn btn-primary">Отправить</button>
        </div>
    </form>
</div>
{% endif %}

<!-- Комментарии -->
{% for item in comments %}
<div class="media card mb-4">
    <div class="media-body card-body">
        <h5 class="mt-0">
            <a href="{% url 'profile' item.author.username %}"
               name="comment_{{ item.id }}">
                {{ item.author.username }}
            </a>
        </h5>
        <p>{{ item.text | linebreaksbr }}</p>
    </div>
</div>
{% endfor %}
{% endblock %}

templates/follow.html
{% extends "base.html" %}
{% block title %} Последние обновления {% endblock %}
{% load user_filters %}


{% block content %}

<div class="container">
    {% include "menu.html" with follow=True %}
    <h1> Последние обновления на сайте</h1>
    {% for post in page %}
    {% include "post_item.html" with post=post %}
    {% endfor %}
</div>

{% if page.has_other_pages %}
{% include "paginator.html" with items=page paginator=paginator %}
{% endif %}

{% endblock %}

templates/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <a href="{% url 'about:author' %}">Об авторе</a>
    <a href="{% url 'about:tech' %}">Технологии</a>
    <p class="m-0 text-dark text-center ">Социальная сеть <span
            style="color:red">Ya</span>tube {% now "Y" %}, все права защищены.
    </p>
</footer>

templates/group.html
{% extends "base.html" %}
{% block title %} Записи сообщества {{group.title}} {% endblock %}
{% block content %}
{% load thumbnail %}

    <h1>{{group.title}}</h1>
    <p>{{group.description}}</p>

    {% for post in page %}
        {% include "post_item.html" with post=post %}
    {% endfor %}

    {% if page.has_other_pages %}
        {% include "paginator.html" with items=page paginator=paginator%}
    {% endif %}

{% endblock %}

templates/header.html
<div id="top-of-site">
  <link rel="icon" href="data:;base64,=">
  <img src="images/logo.jpg" alt="Yatube" />
  <div id="site-name">Yatube</div>
</div>

templates/index.html
{% extends "base.html" %}
{% block title %}Последние обновления {% endblock %}

{% block content %}
<div class="container">

    {% include "menu.html" with index=True %}

        <h1>Последние обновления на сайте</h1>

        {% for post in page %}
            {% include "post_item.html" with post=post %}
        {% endfor %}

        {% if page.has_other_pages %}
            {% include "paginator.html" %}
        {% endif %}

    </div>
{% endblock %}

templates/menu.html
{% if user.is_authenticated %} 
<div class="row">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link {% if index %}active{% endif %}" href="{% url 'index' %}">
                  Все авторы
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if follow %}active{% endif %}" href="/follow">
                Избранные авторы
            </a>
        </li>
    </ul>
</div>
{% endif %}

templates/nav.html
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="{% url 'index' %}"><span style="color:red">Ya</span>tube</a>
    <nav class="my-2 my-md-0 mr-md-3">
        {% if user.is_authenticated %}
        Пользователь: {{ user.username }}.
        <a class="p-2 text-dark" href="{% url 'new_post' %}">Новая запись</a>
        <a class="p-2 text-dark" href="{% url 'password_change' %}">Изменить пароль</a>
        <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>
        {% else %}
        <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a> |
        <a class="p-2 text-dark" href="{% url 'signup' %}">Регистрация</a>
        {% endif %}
    </nav>
</nav>

templates/new.html
{% extends "base.html" %}
{% block title %}Новый пост{% endblock %}
{% block content %}
{% load user_filters %}

<div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">{% if post %}Редактировать запись{% else %}Добавить запись{% endif %}</div>
            <div class="card-body">

              {% for error in form.errors %}
                  <div class="alert alert-danger" role="alert">
                      {{ error|escape }}
                  </div>
                {% endfor %}

                <form method="post" enctype="multipart/form-data" action={% if post %}"{% url 'post_edit' user.username post.id %}"{% else %}"{% url 'new_post' %}"{% endif %}>
                    {% csrf_token %}

                    {% for field in form %}

                        <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                                <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
                                <div class="col-md-6">

                                    {{ field|addclass:"form-control" }}

                                    {% if field.help_text %}
                                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                                    {% endif %}
                                </div>
                        </div>
                    {% endfor %}

                    <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary">
                                {% if post %}
                                    Сохранить
                                {% else %}
                                    Добавить
                                {% endif %}
                            </button>
                    </div>
                </form>
            </div> <!-- card body -->
        </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->

{% endblock %}

templates/paginator.html
{% if page.has_other_pages %}
<nav>
  <ul class="pagination">
    {% if page.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">&laquo; Предыдущая</span>
    </li>
    {% endif %}
    {% for i in page.paginator.page_range %}
    {% if page.number == i %}
    <li class="page-item active">
      <span class="page-link">{{ i }}
        <span class="sr-only">(текущая)</span>
      </span>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="?page={{ i }}">{{ i }}</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if page.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">Следующая &raquo;</span>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

templates/post.html
{% extends "base.html" %}
{% block content %}
{% include "author_card.html" %}
{% load thumbnail %}

        <div class="col-md-9">
            <!-- Пост -->
                {% include "post_item.html" with post=post %}



{% for item in comments %}
<div class="media card mb-4">
    <div class="media-body card-body">
        <h5 class="mt-0">
            <a href="{% url 'profile' item.author.username %}"
               name="comment_{{ item.id }}">
                {{ item.author.username }}
            </a>
        </h5>
        <p>{{ item.text | linebreaksbr }}</p>
    </div>
</div>
{% endfor %}
        </div>

        </div>

</main>
{% endblock %}

templates/post_item.html
<div class="card mb-3 mt-1 shadow-sm">

  <!-- Отображение картинки -->
  {% load thumbnail %}
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
  <img class="card-img" src="{{ im.url }}" />
  {% endthumbnail %}
  <!-- Отображение текста поста -->
  <div class="card-body">
    <p class="card-text">
      <!-- Ссылка на автора через @ -->
      <a name="post_{{ post.id }}" href="{% url 'profile' post.author.username %}">
        <strong class="d-block text-gray-dark">@{{ post.author }}</strong>
      </a>
      {{ post.text|linebreaksbr }}
    </p>

    <!-- Если пост относится к какому-нибудь сообществу, то отобразим ссылку на него через # -->
    {% if post.group %}
    <a class="card-link muted" href="{% url 'group' post.group.slug %}">
      <strong class="d-block text-gray-dark">#{{ post.group.title }}</strong>
    </a>
    {% endif %}

    <!-- Отображение ссылки на комментарии -->
    <div class="d-flex justify-content-between align-items-center">
      <div class="btn-group">

        {% if post.comments.exists %}
        <div>
          Комментариев: {{ post.comments.count }}
        </div>
        {% endif %}
        <a class="btn btn-sm btn-primary" href="{% url 'add_comment' post.author.username post.id %}" role="button">
          Добавить комментарий
        </a>

        <!-- Ссылка на редактирование поста для автора -->
        {% if user == post.author %}
        <a class="btn btn-sm btn-info" href="{% url 'post_edit' post.author.username post.id %}" role="button">
          Редактировать
        </a>
        {% endif %}
      </div>

      <!-- Дата публикации поста -->
      <small class="text-muted">{{ post.pub_date }}</small>
    </div>
  </div>
</div>